//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkTeaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAP
    {
        public string MACTPN { get; set; }
        public string MAPN { get; set; }
        public string MANL { get; set; }
        public Nullable<int> DINHLUONG { get; set; }
        public string MADVT { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
    
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
